version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Shopify.Presentation/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: no
